syntax = "proto3";

package camera;

service CameraService {
  rpc SetZoom (SetZoomRequest) returns (SetZoomResponse) {}
  rpc GetZoom (GetZoomRequest) returns (GetZoomResponse) {}
  rpc SetFocus (SetFocusRequest) returns (SetFocusResponse) {}
  rpc GetFocus (GetFocusRequest) returns (GetFocusResponse) {}
  rpc GetInfo (GetInfoRequest) returns (GetInfoResponse) {}
  rpc GoToMinZoom (GoToMinZoomRequest) returns (GoToMinZoomResponse) {}
  rpc GoToMaxZoom (GoToMaxZoomRequest) returns (GoToMaxZoomResponse) {}
  rpc EnableAutoFocus (EnableAutoFocusRequest) returns (EnableAutoFocusResponse) {}
  rpc Stabilize (EnableStabilizationRequest) returns (EnableStabilizationResponse) {}
}

message SetZoomRequest {
  uint32 zoom = 1;
}

message SetZoomResponse {
}

message GetZoomRequest {
}

message GetZoomResponse {
  uint32 zoom = 1;
}

message SetFocusRequest {
  uint32 focus = 1;
}

message SetFocusResponse {
}

message GetFocusRequest {
}

message GetFocusResponse {
  uint32 focus = 1;
}

message GetInfoRequest {
}

message GetInfoResponse {
  string info = 1;
}

message GoToMinZoomRequest {
}

message GoToMinZoomResponse {
}

message GoToMaxZoomRequest {
}

message GoToMaxZoomResponse {
}

message EnableAutoFocusRequest {
  bool enable = 1;
}

message EnableAutoFocusResponse {
}

message EnableStabilizationRequest {
  bool enable = 1;
}

message EnableStabilizationResponse {
}
