syntax = "proto3";

package camera.v1;

import "google/protobuf/empty.proto";

service CameraService {
  // Zoom operations
  rpc SetZoom (SetZoomRequest) returns (SetZoomResponse) {}
  rpc GetZoom (google.protobuf.Empty) returns (GetZoomResponse) {}
  rpc GoToMinZoom (google.protobuf.Empty) returns (GoToMinZoomResponse) {}
  rpc GoToMaxZoom (google.protobuf.Empty) returns (GoToMaxZoomResponse) {}

  // Focus operations
  rpc SetFocus (SetFocusRequest) returns (SetFocusResponse) {}
  rpc GetFocus (google.protobuf.Empty) returns (GetFocusResponse) {}
  rpc SetAutoFocus (SetAutoFocusRequest) returns (google.protobuf.Empty) {}

  // Device info
  rpc GetInfo (google.protobuf.Empty) returns (GetInfoResponse) {}

  // Advanced operations
  rpc SetStabilization (SetStabilizationRequest) returns (google.protobuf.Empty) {}
}

// Zoom operations
message SetZoomRequest {
  uint32 zoom = 1; // normalized [0 - 100]
}

message SetZoomResponse {
}

message GetZoomResponse {
  uint32 zoom = 1; // normalized [0 - 100]
}

message GoToMinZoomResponse {
}

message GoToMaxZoomResponse {
}

// Focus operations
message SetFocusRequest {
  uint32 focus = 1; // normalized [0 - 100]
}

message SetFocusResponse {
}

message GetFocusResponse {
  uint32 focus = 1; // normalized [0 - 100]
}

message SetAutoFocusRequest {
  bool enable = 1;
}

// Device info
message GetInfoResponse {
  string info = 1;
}

// Advanced operations
message SetStabilizationRequest {
  bool enable = 1;
}